# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20170724_1747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TFModel',
            new_name='Model',
        ),
    ]
